name: Full Diagnostic

on:
  workflow_dispatch:

jobs:
  diagnose:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install tools
        run: |
          pip install jupyter-book pyyaml

      - name: Check structure
        run: |
          echo "=== Repository structure ==="
          tree -L 3 || find . -not -path '*/\.git/*' -type f -o -type d | head -40
          
      - name: Show config files
        run: |
          echo "=== _config.yml contents ==="
          cat notebooks/_config.yml
          echo ""
          echo "=== _toc.yml contents ==="
          cat notebooks/_toc.yml
          echo ""
          echo "=== index.md contents ==="
          cat notebooks/index.md

      - name: Validate YAML
        run: |
          echo "=== Validating _config.yml ==="
          python3 << 'EOF'
          import yaml
          try:
              with open('notebooks/_config.yml') as f:
                  config = yaml.safe_load(f)
              print("✓ _config.yml is valid YAML")
              print(config)
          except Exception as e:
              print(f"✗ _config.yml error: {e}")
              exit(1)
          EOF
          
          echo ""
          echo "=== Validating _toc.yml ==="
          python3 << 'EOF'
          import yaml
          try:
              with open('notebooks/_toc.yml') as f:
                  toc = yaml.safe_load(f)
              print("✓ _toc.yml is valid YAML")
              print(toc)
          except Exception as e:
              print(f"✗ _toc.yml error: {e}")
              exit(1)
          EOF

      - name: Check file references
        run: |
          echo "=== Checking if TOC files exist ==="
          python3 << 'EOF'
          import yaml
          from pathlib import Path
          
          # Load TOC
          with open('notebooks/_toc.yml') as f:
              toc = yaml.safe_load(f)
          
          notebooks_dir = Path('notebooks')
          
          # Check root
          root_file = toc.get('root', 'index')
          root_path = notebooks_dir / f"{root_file}.md"
          if root_path.exists():
              print(f"✓ Root file exists: {root_path}")
          else:
              print(f"✗ Root file missing: {root_path}")
          
          # Check chapters
          chapters = toc.get('chapters', [])
          print(f"\nChecking {len(chapters)} chapters:")
          for chapter in chapters:
              if isinstance(chapter, dict):
                  file_name = chapter.get('file')
                  if file_name:
                      ipynb_path = notebooks_dir / f"{file_name}.ipynb"
                      md_path = notebooks_dir / f"{file_name}.md"
                      if ipynb_path.exists():
                          print(f"✓ {ipynb_path}")
                      elif md_path.exists():
                          print(f"✓ {md_path}")
                      else:
                          print(f"✗ Missing: {file_name}.ipynb or {file_name}.md")
          EOF

      - name: Try building with explicit path
        run: |
          echo "=== Attempting build with ./notebooks ==="
          jupyter-book build ./notebooks 2>&1 || true
          
          echo ""
          echo "=== Checking for _build directory ==="
          if [ -d "notebooks/_build" ]; then
            echo "✓ _build exists"
            find notebooks/_build -type d
            echo ""
            echo "Files in _build:"
            find notebooks/_build -type f | head -20
          else
            echo "✗ _build does not exist"
          fi

      - name: Try alternative build commands
        run: |
          echo "=== Try 1: Build from inside notebooks directory ==="
          cd notebooks
          jupyter-book build . 2>&1 || true
          cd ..
          
          echo ""
          echo "=== Checking results ==="
          if [ -d "notebooks/_build/html" ]; then
            echo "✓ SUCCESS! _build/html exists"
            ls -la notebooks/_build/html/ | head -10
          else
            echo "✗ Still no _build/html"
          fi

      - name: Show full error output
        if: always()
        run: |
          echo "=== If build failed, showing any error logs ==="
          find notebooks/_build -name "*.log" -exec cat {} \; 2>/dev/null || echo "No log files found"
